### ISSUE TITLE
correct / incorrect and shuffle

### ISSUE THREAD

**Issue by harshitaak07** [harshitaak07/app-sesh#5]
In the answer screen , the color of the tile does not change once tapped. Look into it. Also shuffle the options.

**Comment by Saurabhyadav0** [comment]
@harshitaak07 can you assign me this project?

**Comment by tanush077** [comment]
mandatory comment

**Comment by harshitaak07** [comment]
> @harshitaak07 can you assign me this project?
 already assigned to someone else
